// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  // Your custom configs here
).prepend({
  // Generated by `supabase gen types` — not ours to lint
  ignores: ['app/types/database.types.ts']
})
